language: node_js
node_js:
  - "stable"

cache:
  dependencies: node_modules

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  cleanup: true
  domain: piaic-bootcamp2020-rtdd-w-travis.surge.sh
  project: ./build/

on:
  branch: master
